import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});
await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('.art-card').count(),8);
assert(await page.locator('.art-card img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)));
assert(await page.evaluate(()=>document.documentElement.scrollHeight===innerHeight));
await page.mouse.move(1400,900);await page.waitForTimeout(800);
assert((await page.locator('#image-grid').getAttribute('style')).includes('--mx: -'));
await page.screenshot({path:'verification/editorial-light.png'});
await page.locator('#themeToggle').click();await page.screenshot({path:'verification/editorial-dark.png'});
await page.getByRole('button',{name:'About',exact:true}).click();assert(await page.locator('dialog').isVisible());
await page.locator('#contact-from-about').click();assert((await page.locator('dialog h2').innerText()).includes('conversation'));await page.keyboard.press('Escape');
await page.getByRole('link',{name:'Projects'}).click();await page.waitForURL('**/work/');
assert.equal(await page.locator('.project-row').count(),8);
await page.locator('.project-row').nth(1).hover();assert((await page.locator('#floating-preview').getAttribute('src')).includes('off-grid'));
await page.screenshot({path:'verification/editorial-work.png',fullPage:true});
await page.locator('.project-row').nth(1).click();assert((await page.locator('dialog h2').innerText()).includes('Off Grid'));await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:3000');await page.locator('#themeToggle').click();
await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(500);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert(await page.evaluate(()=>document.documentElement.scrollHeight===innerHeight));
await page.screenshot({path:'verification/editorial-mobile.png'});
assert.deepEqual(errors,[]);console.log('PASS: eight images, fullscreen hero, parallax, themes, dialogs, work navigation, hover previews, mobile fit, no browser errors.');await browser.close();
